export const GET_POSTS = 'GET_POSTS';
export const GOOD_POSTS_RESPONSE = 'GOOD_POST_RESPONSE';
export const BAD_POSTS_RESPONSE = 'BAD_POST_RESPONSE';
export const UPDATE_POSTS = 'UPDATE_POSTS';
export const FETCH_POSTS = 'FETCH_POSTS"';